name: Android Check
on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

env:
  JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64  # Java 17 is required for Android Gradle 8 plugin
  QT_DEBUG_PLUGINS: 1

jobs:
  android-check:
    name: Build Android Debug
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavor: [WebDebug, FdroidDebug]
        include:
          - flavor: WebDebug
            arch: arm64
          - flavor: FdroidDebug
            arch: arm32
    steps:
      - name: Install build tools and dependencies
        shell: bash
        run: | 
          sudo apt-get update -y
          sudo apt-get install -y ninja-build \
          qt6-base-dev \
          qt6-declarative-dev \
          qt6-positioning-dev \
          libqt6svg6-dev \
          optipng \
          libfreetype-dev \
          libharfbuzz-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libxi-dev \
          zlib1g-dev
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 200 # enough to get all commits for the current day

      - name: Parallel submodules checkout
        shell: bash
        run: git submodule update --depth 1 --init --recursive --jobs=$(($(nproc) * 20))

      - name: Configure repository
        shell: bash
        run: ./configure.sh

      - name: Generate symbols
        shell: bash
        run: ./tools/unix/generate_symbols.sh

      - name: Compile ${{ matrix.flavor }}
        shell: bash
        working-directory: android
        run: |
          cmake --version
          ninja --version
          ./gradlew -P${{ matrix.arch }} assemble${{ matrix.flavor }}

      - name: Upload ${{ matrix.flavor }} apk
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ matrix.flavor }}
          path: android/app/build/outputs/apk/**/CoMaps-*.apk
          if-no-files-found: error
